name: alo_moves
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  go_router: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.2
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  lint: ^2.1.2

flutter_gen:
  output: lib/generated/

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/json/
